#![cfg(test)]

use super::*;
use soroban_sdk::{testutils::Address as _, token::{Client as TokenClient, StellarAssetClient}, Address, Env};

fn setup_test() -> (Env, Address, SariPayB2BContractClient<'static>, Address, Address, TokenClient<'static>, StellarAssetClient<'static>) {
    let env = Env::default();
    env.mock_all_auths();

    let contract_id = env.register(SariPayB2BContract, ());
    let client = SariPayB2BContractClient::new(&env, &contract_id);

    let merchant = Address::generate(&env);
    let distributor = Address::generate(&env);
    let token_admin = Address::generate(&env);

    let token_contract = env.register_stellar_asset_contract_v2(token_admin);
    let token = TokenClient::new(&env, &token_contract.address());
    let token_admin_client = StellarAssetClient::new(&env, &token_contract.address());

    (env, contract_id, client, merchant, distributor, token, token_admin_client)
}

#[test]
fn test_1_happy_path() {
    let (env, contract_id, client, merchant, distributor, token, token_admin) = setup_test();

    token_admin.mint(&merchant, &1000);

    let order_id = 1u64;
    let amount = 500i128;

    client.init_order(&order_id, &merchant, &distributor, &token.address, &amount);
    client.fund_order(&order_id);

    let contract_address = env.as_contract(&contract_id, || env.current_contract_address());
    assert_eq!(token.balance(&contract_address), 500);

    client.confirm_delivery(&order_id);

    assert_eq!(token.balance(&distributor), 500);
    assert_eq!(token.balance(&contract_address), 0);
}

#[test]
fn test_2_confirm_delivery_unfunded_failure() {
    let (_env, _contract_id, client, merchant, distributor, token, _) = setup_test();

    let order_id = 2u64;
    let amount = 300i128;

    client.init_order(&order_id, &merchant, &distributor, &token.address, &amount);
    
    // Fixed: Using try_confirm_delivery natively generated by Soroban instead of catch_unwind
    let result = client.try_confirm_delivery(&order_id);
    assert!(result.is_err());
}

#[test]
fn test_3_state_verification() {
    let (env, contract_id, client, merchant, distributor, token, token_admin) = setup_test();

    token_admin.mint(&merchant, &500);

    let order_id = 3u64;
    let amount = 300i128;

    client.init_order(&order_id, &merchant, &distributor, &token.address, &amount);
    client.fund_order(&order_id);

    let key = DataKey::Order(order_id);
    
    let stored_order: SupplyOrder = env.as_contract(&contract_id, || {
        env.storage().instance().get(&key).unwrap()
    });

    assert_eq!(stored_order.status, OrderStatus::Funded);

    let contract_address = env.as_contract(&contract_id, || env.current_contract_address());
    assert_eq!(token.balance(&contract_address), 300);
}

#[test]
fn test_4_cannot_fund_twice() {
    let (_env, _contract_id, client, merchant, distributor, token, token_admin) = setup_test();

    token_admin.mint(&merchant, &1000);

    let order_id = 4u64;
    let amount = 300i128;

    client.init_order(&order_id, &merchant, &distributor, &token.address, &amount);
    client.fund_order(&order_id);

    // Fixed: Using try_fund_order natively generated by Soroban instead of catch_unwind
    let result = client.try_fund_order(&order_id);
    assert!(result.is_err());
}

#[test]
fn test_5_distributor_cancel_with_refund() {
    let (env, contract_id, client, merchant, distributor, token, token_admin) = setup_test();

    token_admin.mint(&merchant, &500);

    let order_id = 5u64;
    let amount = 300i128;

    client.init_order(&order_id, &merchant, &distributor, &token.address, &amount);
    client.fund_order(&order_id);

    client.cancel_order(&order_id);

    assert_eq!(token.balance(&merchant), 500);

    let key = DataKey::Order(order_id);
    
    let stored_order: SupplyOrder = env.as_contract(&contract_id, || {
        env.storage().instance().get(&key).unwrap()
    });

    assert_eq!(stored_order.status, OrderStatus::Canceled);
}